(function(x,q,r,b,v,Q){function w(d){return!isNaN(parseFloat(d))&&isFinite(d)}function A(d){return RegExp(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i).test(d)}function E(d){return RegExp(/^[0-9a-f]{32}$/i).test(d)}function F(d,b,c){d=d||[];var a=this,g=Math.floor((new Date).getTime()/1E3);a._session={rtgsession_ts_creation_cookie:d[0],rtgsession_ttl:d[1],rtgsession_seq:d[2],rtgsession_id_prev:d[3],rtgsession_id:d[4],rtgsession_ts:d[5],rtgsession_hits:d[6]};a.setUpNewSession=
function(){a._session.rtgsession_id=b+":"+g;a._session.rtgsession_ts=g;a._session.rtgsession_hits=1};a.setUpNewSessionHeader=function(){a._session.rtgsession_ts_creation_cookie=g;a._session.rtgsession_ttl=c;a._session.rtgsession_seq=1;a._session.rtgsession_id_prev=""};a.getValue=function(){return a._session.rtgsession_ts_creation_cookie+"_"+a._session.rtgsession_ttl+"_"+a._session.rtgsession_seq+"_"+a._session.rtgsession_id_prev+"_"+a._session.rtgsession_id+"_"+a._session.rtgsession_ts+"_"+a._session.rtgsession_hits};
a.getEncodedValue=function(){return encodeURIComponent(a.getValue())};a.createNew=function(){a.setUpNewSessionHeader();a.setUpNewSession()};a.checkError=function(){function c(a,b){d.isValid=!1;d.msg+=d.msg?"|"+a:a}function b(a){if(a&&(a=a.split(":"),a.length&&2===a.length))return A(a[0])&&w(a[1])}var d={isValid:!0,msg:""};try{w(a._session.rtgsession_ts_creation_cookie)?a._session.rtgsession_ts_creation_cookie=parseFloat(a._session.rtgsession_ts_creation_cookie):c("rtgsession_ts_creation_cookie"),
w(a._session.rtgsession_ttl)?a._session.rtgsession_ttl=parseFloat(a._session.rtgsession_ttl):c("rtgsession_ttl"),w(a._session.rtgsession_seq)?a._session.rtgsession_seq=parseFloat(a._session.rtgsession_seq):c("rtgsession_seq"),a._session.rtgsession_id_prev&&!b(a._session.rtgsession_id_prev)?c("rtgsession_id_prev"):(a._session.rtgsession_id_prev_uid=a._session.rtgsession_id_prev.split(":")[0],a._session.rtgsession_id_prev_ts=parseFloat(a._session.rtgsession_id_prev.split(":")[1])),a._session.rtgsession_id&&
!b(a._session.rtgsession_id)?c("rtgsession_id"):(a._session.rtgsession_id_uid=a._session.rtgsession_id.split(":")[0],a._session.rtgsession_id_ts=parseFloat(a._session.rtgsession_id.split(":")[1])),w(a._session.rtgsession_ts)?a._session.rtgsession_ts=parseFloat(a._session.rtgsession_ts):c("rtgsession_ts"),g<parseFloat(a._session.rtgsession_ts)&&c("rtgsession_duration"),w(a._session.rtgsession_hits)||c("rtgsession_hits")}catch(f){l(d.msg+"+checkError+function+failed&trossion="+a.getEncodedValue()+"&timestamp="+
a.timeStamp,G)}return d};a.updateWithNewSession=function(){a._session.rtgsession_seq=parseFloat(a._session.rtgsession_seq)+1;a._session.rtgsession_id_prev=a._session.rtgsession_id;a.setUpNewSession()};a.updateSession=function(){a._session.rtgsession_ts=g;a._session.rtgsession_hits=parseFloat(a._session.rtgsession_hits)+1};a.updateEv=function(c){c=c||{};c.rtgsession_ts_creation_cookie=a._session.rtgsession_ts_creation_cookie;c.rtgsession_ttl=a._session.rtgsession_ttl;c.rtgsession_seq=a._session.rtgsession_seq;
c.rtgsession_id_prev=a._session.rtgsession_id_prev;c.rtgsession_id_prev_uid=a._session.rtgsession_id_prev_uid;c.rtgsession_id_prev_ts=a._session.rtgsession_id_prev_ts;c.rtgsession_id=a._session.rtgsession_id;c.rtgsession_id_uid=a._session.rtgsession_id_uid;c.rtgsession_id_ts=a._session.rtgsession_id_ts;c.rtgsession_ts=a._session.rtgsession_ts;c.rtgsession_hits=a._session.rtgsession_hits;c.rtgsession_duration=a._session.rtgsession_duration;c.rtgsession_seq_duration=a._session.rtgsession_seq_duration;
return c};a.getSessionForTagContainer=function(){return[["rtgsession_ts_creation_cookie",[a._session.rtgsession_ts_creation_cookie]],["rtgsession_ttl",[a._session.rtgsession_ttl]],["rtgsession_seq",[a._session.rtgsession_seq]],["rtgsession_id_prev",[a._session.rtgsession_id_prev]],["rtgsession_id_prev_uid",[a._session.rtgsession_id_prev_uid]],["rtgsession_id_prev_ts",[a._session.rtgsession_id_prev_ts]],["rtgsession_id",[a._session.rtgsession_id]],["rtgsession_id_uid",[a._session.rtgsession_id_uid]],
["rtgsession_id_ts",[a._session.rtgsession_id_ts]],["rtgsession_ts",[a._session.rtgsession_ts]],["rtgsession_hits",[a._session.rtgsession_hits]],["rtgsession_duration",[a._session.rtgsession_duration]],["rtgsession_seq_duration",[a._session.rtgsession_seq_duration]]]};(function(a){if(7>d.length)a.createNew();else{var b=a.checkError();b.isValid?g-parseFloat(a._session.rtgsession_ts)>c?a.updateWithNewSession():a.updateSession():(l(b.msg+"&trossion="+a.getEncodedValue()+"&timestamp="+a.timeStamp,G),
a.createNew())}a._session.rtgsession_id_ts&&a._session.rtgsession_ts&&(a._session.rtgsession_duration=a._session.rtgsession_ts-parseFloat(a._session.rtgsession_id_ts));a._session.rtgsession_id_ts&&a._session.rtgsession_id_prev_ts&&(a._session.rtgsession_seq_duration=a._session.rtgsession_ts-a._session.rtgsession_id_prev_ts)})(a);return a}function H(d,f){function c(){return[{id:"default",version:1,ttl:30,events:[{coef:-0.1071305787347127},{coef:0.216131896556964,cond:"rtgsession_seq"},{coef:1.2656065071142095E-4,
cond:"rtgsession_duration"},{coef:0.07467899685829335,cond:"rtgsession_hits"}]}]}function a(a){try{return c().map(function(c){return s(c,a)})}catch(b){return l(b+"createNewScore: return score empty",n),c()}}function g(a,c){try{var b=parseFloat(a.value),d=parseFloat(a.lower_bound_value),f=parseFloat(a.upper_bound_value),t=parseFloat(c[a.key]);switch(a.operator){case "BETWEEN":return t>d&&t<f;case "==":return c[a.key]===a.value;case "<=":return t<=b;case ">=":return t>=b;case ">":return t>b;case "<":return t<
b;case "AND":return a.valueA&&a.valueB;case "OR":return a.valueA||a.valueB;case "IS NOT NULL":return c.hasOwnProperty(a.key)&&""!==c[a.key]&&void 0!==c[a.key];case "NOT":return!a.value;case "REGEXP":return RegExp(a.value,"giu").test(c[a.key]);default:l(e+error.msg+"+operator not supported for visitor scoring",n)}}catch(h){l(h+"evaluateExpression",n)}}function m(a){try{var c=[];if("string"===typeof a&&0<a.length)for(var b=a.split(" ");b&&0<b.length;){var d=b.shift();if('"'===d[0]){if('"'!==d[d.length-
1])for(;;){var f=b.shift();if(void 0===f){d=void 0;break}d=d+" "+f;if('"'===f[f.length-1])break}void 0!==d&&(d=d.substring(1,d.length-1))}"IS"==d&&"NULL"===b[0]&&(d=d+" "+b.shift());"IS"==d&&("NOT"===b[0]&&"NULL"===b[1])&&(d=d+" "+b.shift()+" "+b.shift());void 0!==d&&c.push(d)}return c}catch(t){l(t+"lexer",n)}return[]}function k(a,c){var d=[];try{m(a).forEach(function(a){var b={operator:a};switch(a){case "BETWEEN":b.upper_bound_value=d.pop();b.lower_bound_value=d.pop();b.key=d.pop();a=g(b,c);break;
case "==":case "<=":case ">=":case ">":case "<":case "REGEXP":b.value=d.pop();b.key=d.pop();a=g(b,c);break;case "AND":case "OR":b.valueB=d.pop();b.valueA=d.pop();a=g(b,c);break;case "NOT":b.value=d.pop();a=g(b,c);break;case "IS NOT NULL":b.key=d.pop();a=g(b,c);break;case "!=":b.value=d.pop();b.key=d.pop();a=k(b.key+" "+b.value+" == NOT",c);break;case "IS NULL":b.key=d.pop(),a=k(b.key+" IS NOT NULL NOT",c)}d.push(a)})}catch(b){l(b+"processReversePolishNotation",n)}return d.pop()}function s(a,c){function b(a,
c){return function(b,d){try{var f=0,h=k(d.cond,c);if(void 0!==h)if("boolean"===typeof h){if(void 0===d.incr||a)d.incr=0;h&&(d.incr+=1);f=d.coef*d.incr}else f=d.coef*parseFloat(c[h])||0;else f=d.coef||0;return b+f}catch(g){return l(g+"setScore: scoreReducer: no score increment",n),b}}}try{var d=a.events.reduce(b(void 0===a.ts||c.rtgsession_ts-a.ts>86400*a.ttl,c),0);a.score=Math.floor(1E3/(1+Math.exp(-d)));a.ts=c.rtgsession_ts}catch(f){l(f+"setScore: could not compute score",n)}return a}function q(a){var c=
{isValid:!0,msg:""};try{c=h.models.reduce(function(a,d){try{d.events.forEach(function(a){if(""===a.coef||void 0===a.coef)c.isValid=!1,c.msg+=c.msg?"|coef":"coef"})}catch(b){l(b+c.msg+"+checkError+function+failed&engagement",n)}return a},c)}catch(d){l(d+c.msg+"+checkError+function+failed&engagement",n)}return c}var h=this;h.models=[];var r=function(a){try{var c=a.filter(function(a){return"default"!==a.id});if(0<c.length)return encodeURIComponent(JSON.stringify(c))}catch(d){l(d+"stringifyModels",n)}return""},
p=function(){return r(h.models)};(function(d,b){try{var f=h,g;a:{try{if(d&&0<d.length){g=JSON.parse(decodeURIComponent(d));break a}}catch(k){l(k+"parseModels",n)}g=[]}f.models=g;0===h.models.length&&(h.models=c());var t=q(h.models);t.isValid?h.models=h.models.map(function(a){return s(a,b)}):(l(t.msg+"init+function+failed+model+not+valid+&engagement="+n),h.models=a(b))}catch(m){l(m+"+init+function+failed&engagement",n),h.models=a(b)}})(d,f);h.lexer=m;h.evaluateExpression=g;h.processReversePolishNotation=
k;h.getScores=function(a){function c(a,d,b){return a+"&"+d}function d(a){return void 0!==a?"rtg"+a.id+"_score="+encodeURIComponent(a.score)+"&rtg"+a.id+"_version="+encodeURIComponent(a.version):""}try{if(0<h.models.length)return h.models.map(d).reduce(c);l("+getScores+function+empty+models&engagement",n)}catch(b){l(b+"getScore",n)}return""};h.getScoresForTagContainer=function(){try{if(0<h.models.length)return h.models.reduce(function(a,c){a.push(["rtg"+c.id+"_score",[c.score]]);a.push(["rtg"+c.id+
"_version",[c.version]]);return a},[])}catch(a){l(a+"getScoresForTagContainer",n)}return[]};h.getEncodedModels=p;h.updateEv=function(a){function c(a,d){a["rtg"+d.id+"_score"]=d.score;a["rtg"+d.id+"_version"]=d.version;return a}try{0<h.models.length&&(a=h.models.reduce(c,a))}catch(d){l(d+"+updateEv fail",n)}return a};h.writeNewModelsToCookie=function(a){try{for(var c=[],d=h.models.reduce(function(a,c){a[c.id]=c;return a},{}),f=0;f<a.length;f+=1){var g=a[f];if(void 0!==d[g.id]){for(var k=0;k<g.events.length;k+=
1)d[g.id].events[k].coef=g.events[k].coef;d[g.id].version=g.version;c.push(d[g.id])}else c.push(a[f])}h.models=c;B("__trossion",b._session.getValue()+"_"+p(),185)}catch(s){l(s+"+writeNewModelsToCookie fail",n)}};return h}function I(d){try{var f=Array.prototype.slice.call(arguments,0);d=f.shift();switch(d){case "init":b.tagid||(b.tagid=f[0],J());break;case "session_ttl":f[0]&&(b.session_ttl=f[0]);break;case "tag":u=[];var c=f[0],f=[],a;for(a in c)if(c.hasOwnProperty(a))if("rtg"===a.substring(0,3))u.push(y(a,
[c[a]])),f.push([a,[c[a]]]);else if("exclusion"===a)u.push("exclusion=1"),f.push([a,["1"]]);else if("m5e"===a||"sha256"===a||"email"===a)u.push(y(a,[c[a]])),f.push([a,[c[a]]]);K(u,f,c)}}catch(g){l(g,R)}}function K(d,f,c){try{f.push(["r1",[m]]);c.r1=m;f.push(["vruid",[v]]);c.vruid=v;if(null!==p&&""!==p){var a;try{a=encodeURIComponent(p)}catch(g){a=escape(p)}f.push(["u",[a]]);c.u=a}var n=b.etag+"_"+(b.version?b.version:"0");f.push(["v",[n]]);c.v=n;if(b.tcf_consent){var k=z("__trossion").split("_"),
s=k.splice(7);b._session=new F(k,b.uid,b.session_ttl);b._session.updateEv(c);f=f.concat(b._session.getSessionForTagContainer());b._en=new H(s.join("_"),c);b._en.updateEv(c);d.push("trossion="+b._session.getEncodedValue())}if(!b.tagid)throw"tagid is missing";b.tcf_consent&&(d.push(b._en.getScores()),f=f.concat(b._en.getScoresForTagContainer()));""!=b.tcf_consent_string&&d.push("gdpr_consent="+b.tcf_consent_string);L(d);b.tcf_consent&&B("__trossion",b._session.getValue()+"_"+b._en.getEncodedModels(),
185);b.segq.queue?b.segq.tag?b.segq.tag.apply(b.segq,c):b.segq.queue.push(c):b.segq.push.apply(b.segq,f)}catch(q){l(q,M)}}function N(){if(!b.unqueue_called){try{if(b.queue)for(;b.queue.length;){var d=b.queue.shift();I.apply(this,d)}else u=Array.prototype.splice.call(b,0),b.push()}catch(f){l(f,ERROR_UNQUEUE)}b.unqueue_called=!0}}function O(d){try{d.queue&&(d=d.queue);for(var b=0;b<d.length;b++)if(d[b]&&d[b][0]&&("tagid"===d[b][0]||"init"===d[b][0])&&""!==d[b][1]){var c=d[b][1].split("-");if(2!=c.length)throw"Tagid is misstructured"+
encodeURIComponent(d[b][1]);if(!c[1]||!E(c[1]))throw"Tag hash is invalid"+encodeURIComponent(c[1]);if(!c[0]||!w(c[0]))throw"Tagid is invalid"+encodeURIComponent(c[0]);if(0!==c[0].indexOf("6"))throw"Tagid identifier is not valid  "+encodeURIComponent(c[0]);return d[b][1]}throw"Tagid is missing";}catch(a){l(a,S)}}x._troqck=x._troqck||0;if(!x._troqck){var C,P=!1,m="",p=r,M=3,S=13,R=14,G=17,n=20;r=p.hostname.split(".").reverse();b.etag=Q;C=2<r.length&&3>=r[1].length&&2>=r[0].length?"."+r[2]+"."+r[1]+
"."+r[0]:"."+r[1]+"."+r[0];x!==top&&(q.referrer&&""!==q.referrer)&&(p=q.referrer);var y=function(d,b){for(var c="",a=0;a<b.length;a++)0<a&&(c+="|"),c+=b[a];try{c=d+"="+encodeURIComponent(c)}catch(g){c=d+"="+escape(c)}return c};b.urlize=y;var z=function(d){var b,c,a,g=q.cookie.split(";");for(b=0;b<g.length;b++)if(c=g[b].substr(0,g[b].indexOf("=")),a=g[b].substr(g[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c===d)try{return decodeURIComponent(a)}catch(l){return unescape(a)}return""};b.getCookie=
z;var B=function(b,f,c){var a=new Date;a.setDate(a.getDate()+c);var g=f;try{f=encodeURIComponent(f)}catch(n){f=escape(f)}var k=f;c=null===c?"":"; expires="+a.toUTCString();k=k+c+("; domain="+C+"; path=/; samesite=lax; secure");q.cookie=b+"="+k;try{var s=z(b);if(""===s||s!=g){var m=x.location.hostname;if(1===m.split(".").length)q.cookie=b+"="+f+c+"; path=/; samesite=lax; secure";else{var h=m.split(".");h.shift();var p="."+h.join(".");q.cookie=b+"="+f+c+"; path=/; domain="+p+"; samesite=lax; secure";
s=z(b);if(""===s||s!=g)q.cookie=b+"="+f+c+"; path=/; domain="+C+"; samesite=lax; secure"}}}catch(r){l(r,1)}};b.setCookie=B;b.isNumeric=w;b.isValidRUID=A;b.isMD5Valid=E;b.Session=F;b.Engagement=H;var L=function(d,f){try{if(null==b.tagid||""===b.tagid)throw"tagid is missing";var c="tagid="+b.tagid+"&";b.tcf_consent&&(c+="r1="+m+"&",c+="vruid="+v+"&");for(;0<d.length;)c+=d.shift()+"&";if(null!==p&&""!==p){c+="u=";try{c+=encodeURIComponent(p)}catch(a){c+=escape(p)}c+="&"}c+="v="+b.etag+"_";c+=(b.version?
b.version:"0")+"&";c+="rnd="+Math.round(2E9*Math.random());c="https://"+(f||"mmtro.com")+"/p?"+c;(new Image(1,1)).src=c}catch(g){l(g,M)}};b.troPix=L;b.push=function(){try{for(var d=0;d<arguments.length;d++)u.push(arguments[d])}catch(f){l(f,4)}for(var d=[],c=[],a=[],g={};0<u.length;)try{var n=u.shift(),k=n.shift();if(!k)throw"empty array in taggage";var k=k.toLowerCase(),m=n,p=!1;if("tagid"===k)b.tagid||(b.tagid=O([[k,m[0]]])),p=!0;else if("rtg"===k.substring(0,3)||-1!==k.indexOf("_")){0===k.indexOf("_")&&
(k=k.substring(1,k.length));var h=y(k,m);c.push(h);a.push([k,m]);g[k]=h.split("=")[1]}else"exclusion"===k?(c.push("exclusion=1"),a.push([k,["1"]]),g.exclusion="1"):"m5e"===k||"sha256"===k||"email"===k?(h=y(k,m),c.push(h),a.push([k,m]),g[k]=h.split("=")[1]):d.push(y(k,m))}catch(q){l(q,5)}0<d.length&&l("wrong params in taggage "+d.join("&"),12);try{0<c.length||p?K(c,a,g):l("p is empty",16)}catch(r){l(r,6)}};b.callTro=I;b.unqueue=N;var D=function(b){var f=q.createElement("script");f.type="text/javascript";
f.async=!0;f.src=b;b=q.getElementsByTagName("script")[0];b.parentNode.insertBefore(f,b)};b.createScript=D;b.jarSyncMMTRO=function(b){};var l=function(d,f){d=d.message||d;d=encodeURIComponent(d.replace(/ /g,"_"));var c="https://err.mmtro.com/error?f=tro.js&u="+encodeURIComponent(x.location.href)+"&message="+d+"&try="+f+"&v="+b.etag+"_"+(b.version?b.version:"0");(new Image(1,1)).src=c},J=function(){if(null!=b.tagid&&""!=b.tagid&&b.tcf_consent){if("00000000-0000-0000-0000-000000000000"!==m)try{D("https://cdn.mmtro.com/seg/"+
b.tagid.split("-")[0]+".js")}catch(d){l(d,8)}D("https://mmtro.com/trojs/"+b.tagid+"/"+m+"/"+v+"/exec.js")}};try{var u=[];b.segq=b.segq||[];if(null==v||""==v||!A(v))throw"vruid is invalid";b.tcf_consent=!0;b.tcf_consent_string="";"function"===typeof __tcfapi&&__tcfapi("getTCData",2,function(d,f){b.tcf_consent_string=d.tcString;if(f){var c=d.vendor.consents[388];b.tcf_consent=d.purpose.consents[1]&&c}});b.tcf_consent&&(m=z("__troRUID"),A(m)||(m&&l("ruid1 not valid: "+encodeURIComponent(m),18),P=!0,
m=v),b.uid=m);b.session_ttl=1800;b.tagid=O(b);N();P&&B("__troRUID",m,185);J()}catch(T){l(T,11)}x._troqck=1}})
(window, document, location, _troq, "02f5cfbd-e899-47be-a53b-954b3e7c4648", "357b5df68d10e2bc2fb67e29");